test_task_template: &TEST_TASK_TEMPLATE
  modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  deps_script: make deps
  clean_script: make clean
  bin_script: make bin
  test_script: make test

linux_test_task:
  env:
    matrix:
      - VERSION: 1.17
      - VERSION: 1.18
  name: Tests (Go $VERSION)
  container:
    image: golang:$VERSION
  <<: *TEST_TASK_TEMPLATE

linux_arm64_test_task:
  env:
    matrix:
      - VERSION: 1.17
      - VERSION: 1.18
  name: Tests (Go $VERSION)
  arm_container:
    image: golang:$VERSION
  <<: *TEST_TASK_TEMPLATE

macos_arm64_test_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  pre_req_script: brew install gox
  <<: *TEST_TASK_TEMPLATE

lint_task:
  name: GolangCI Lint
  container:
    image: golangci/golangci-lint:latest
  run_script: golangci-lint run -v --out-format json > lint-report.json
  always:
    golangci_artifacts:
      path: lint-report.json
      type: text/json
      format: golangci