# Make sure to check the documentation at https://goreleaser.com
version: 2
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin    
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/pact-foundation/pact-go/v2/command.Version={{.Tag}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  groups:
    - title: "Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Other changes"
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^wip:'
      - '^ci:'
      - 'Merge branch'
      - 'Merge pull request'
