FROM golang:latest

RUN apt-get update && apt-get install -y openjdk-17-jre file

COPY . /go/src/github.com/pact-foundation/pact-go

WORKDIR /go/src/github.com/pact-foundation/pact-go

CMD ["make", "test"]