// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugin.proto

package native

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CatalogueEntry_EntryType int32

const (
	// Matcher for contents of messages, requests or response bodies
	CatalogueEntry_CONTENT_MATCHER CatalogueEntry_EntryType = 0
	// Generator for contents of messages, requests or response bodies
	CatalogueEntry_CONTENT_GENERATOR CatalogueEntry_EntryType = 1
	// Mock server for a network protocol
	CatalogueEntry_MOCK_SERVER CatalogueEntry_EntryType = 2
	// Matching rule for content field/values
	CatalogueEntry_MATCHER CatalogueEntry_EntryType = 3
	// Type of interaction
	CatalogueEntry_INTERACTION CatalogueEntry_EntryType = 4
)

var CatalogueEntry_EntryType_name = map[int32]string{
	0: "CONTENT_MATCHER",
	1: "CONTENT_GENERATOR",
	2: "MOCK_SERVER",
	3: "MATCHER",
	4: "INTERACTION",
}

var CatalogueEntry_EntryType_value = map[string]int32{
	"CONTENT_MATCHER":   0,
	"CONTENT_GENERATOR": 1,
	"MOCK_SERVER":       2,
	"MATCHER":           3,
	"INTERACTION":       4,
}

func (x CatalogueEntry_EntryType) String() string {
	return proto.EnumName(CatalogueEntry_EntryType_name, int32(x))
}

func (CatalogueEntry_EntryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{1, 0}
}

// Enum of content type override. This is a hint on how the content type should be treated.
type Body_ContentTypeHint int32

const (
	// Determine the form of the content using the default rules of the Pact implementation
	Body_DEFAULT Body_ContentTypeHint = 0
	// Contents must always be treated as a text form
	Body_TEXT Body_ContentTypeHint = 1
	// Contents must always be treated as a binary form
	Body_BINARY Body_ContentTypeHint = 2
)

var Body_ContentTypeHint_name = map[int32]string{
	0: "DEFAULT",
	1: "TEXT",
	2: "BINARY",
}

var Body_ContentTypeHint_value = map[string]int32{
	"DEFAULT": 0,
	"TEXT":    1,
	"BINARY":  2,
}

func (x Body_ContentTypeHint) String() string {
	return proto.EnumName(Body_ContentTypeHint_name, int32(x))
}

func (Body_ContentTypeHint) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{4, 0}
}

// Type of markup used
type InteractionResponse_MarkupType int32

const (
	// CommonMark format
	InteractionResponse_COMMON_MARK InteractionResponse_MarkupType = 0
	// HTML format
	InteractionResponse_HTML InteractionResponse_MarkupType = 1
)

var InteractionResponse_MarkupType_name = map[int32]string{
	0: "COMMON_MARK",
	1: "HTML",
}

var InteractionResponse_MarkupType_value = map[string]int32{
	"COMMON_MARK": 0,
	"HTML":        1,
}

func (x InteractionResponse_MarkupType) String() string {
	return proto.EnumName(InteractionResponse_MarkupType_name, int32(x))
}

func (InteractionResponse_MarkupType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{15, 0}
}

// Request to verify the plugin has loaded OK
type InitPluginRequest struct {
	// Implementation calling the plugin
	Implementation string `protobuf:"bytes,1,opt,name=implementation,proto3" json:"implementation,omitempty"`
	// Version of the implementation
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitPluginRequest) Reset()         { *m = InitPluginRequest{} }
func (m *InitPluginRequest) String() string { return proto.CompactTextString(m) }
func (*InitPluginRequest) ProtoMessage()    {}
func (*InitPluginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{0}
}

func (m *InitPluginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitPluginRequest.Unmarshal(m, b)
}
func (m *InitPluginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitPluginRequest.Marshal(b, m, deterministic)
}
func (m *InitPluginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitPluginRequest.Merge(m, src)
}
func (m *InitPluginRequest) XXX_Size() int {
	return xxx_messageInfo_InitPluginRequest.Size(m)
}
func (m *InitPluginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitPluginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitPluginRequest proto.InternalMessageInfo

func (m *InitPluginRequest) GetImplementation() string {
	if m != nil {
		return m.Implementation
	}
	return ""
}

func (m *InitPluginRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// Entry to be added to the core catalogue. Each entry describes one of the features the plugin provides.
// Entries will be stored in the catalogue under the key "plugin/$name/$type/$key".
type CatalogueEntry struct {
	// Entry type
	Type CatalogueEntry_EntryType `protobuf:"varint,1,opt,name=type,proto3,enum=io.pact.plugin.CatalogueEntry_EntryType" json:"type,omitempty"`
	// Entry key
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// Associated data required for the entry. For CONTENT_MATCHER and CONTENT_GENERATOR types, a "content-types"
	// value (separated by semi-colons) is required for all the content types the plugin supports.
	Values               map[string]string `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CatalogueEntry) Reset()         { *m = CatalogueEntry{} }
func (m *CatalogueEntry) String() string { return proto.CompactTextString(m) }
func (*CatalogueEntry) ProtoMessage()    {}
func (*CatalogueEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{1}
}

func (m *CatalogueEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CatalogueEntry.Unmarshal(m, b)
}
func (m *CatalogueEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CatalogueEntry.Marshal(b, m, deterministic)
}
func (m *CatalogueEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CatalogueEntry.Merge(m, src)
}
func (m *CatalogueEntry) XXX_Size() int {
	return xxx_messageInfo_CatalogueEntry.Size(m)
}
func (m *CatalogueEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_CatalogueEntry.DiscardUnknown(m)
}

var xxx_messageInfo_CatalogueEntry proto.InternalMessageInfo

func (m *CatalogueEntry) GetType() CatalogueEntry_EntryType {
	if m != nil {
		return m.Type
	}
	return CatalogueEntry_CONTENT_MATCHER
}

func (m *CatalogueEntry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CatalogueEntry) GetValues() map[string]string {
	if m != nil {
		return m.Values
	}
	return nil
}

// Response to init plugin, providing the catalogue entries the plugin provides
type InitPluginResponse struct {
	// List of entries the plugin supports
	Catalogue            []*CatalogueEntry `protobuf:"bytes,1,rep,name=catalogue,proto3" json:"catalogue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InitPluginResponse) Reset()         { *m = InitPluginResponse{} }
func (m *InitPluginResponse) String() string { return proto.CompactTextString(m) }
func (*InitPluginResponse) ProtoMessage()    {}
func (*InitPluginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{2}
}

func (m *InitPluginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitPluginResponse.Unmarshal(m, b)
}
func (m *InitPluginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitPluginResponse.Marshal(b, m, deterministic)
}
func (m *InitPluginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitPluginResponse.Merge(m, src)
}
func (m *InitPluginResponse) XXX_Size() int {
	return xxx_messageInfo_InitPluginResponse.Size(m)
}
func (m *InitPluginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitPluginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitPluginResponse proto.InternalMessageInfo

func (m *InitPluginResponse) GetCatalogue() []*CatalogueEntry {
	if m != nil {
		return m.Catalogue
	}
	return nil
}

// Catalogue of Core Pact + Plugin features
type Catalogue struct {
	// List of entries from the core catalogue
	Catalogue            []*CatalogueEntry `protobuf:"bytes,1,rep,name=catalogue,proto3" json:"catalogue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Catalogue) Reset()         { *m = Catalogue{} }
func (m *Catalogue) String() string { return proto.CompactTextString(m) }
func (*Catalogue) ProtoMessage()    {}
func (*Catalogue) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{3}
}

func (m *Catalogue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Catalogue.Unmarshal(m, b)
}
func (m *Catalogue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Catalogue.Marshal(b, m, deterministic)
}
func (m *Catalogue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Catalogue.Merge(m, src)
}
func (m *Catalogue) XXX_Size() int {
	return xxx_messageInfo_Catalogue.Size(m)
}
func (m *Catalogue) XXX_DiscardUnknown() {
	xxx_messageInfo_Catalogue.DiscardUnknown(m)
}

var xxx_messageInfo_Catalogue proto.InternalMessageInfo

func (m *Catalogue) GetCatalogue() []*CatalogueEntry {
	if m != nil {
		return m.Catalogue
	}
	return nil
}

// Message representing a request, response or message body
type Body struct {
	// The content type of the body in MIME format (i.e. application/json)
	ContentType string `protobuf:"bytes,1,opt,name=contentType,proto3" json:"contentType,omitempty"`
	// Bytes of the actual content
	Content *wrapperspb.BytesValue `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Content type override to apply (if required). If omitted, the default rules of the Pact implementation
	// will be used
	ContentTypeHint      Body_ContentTypeHint `protobuf:"varint,3,opt,name=contentTypeHint,proto3,enum=io.pact.plugin.Body_ContentTypeHint" json:"contentTypeHint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Body) Reset()         { *m = Body{} }
func (m *Body) String() string { return proto.CompactTextString(m) }
func (*Body) ProtoMessage()    {}
func (*Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{4}
}

func (m *Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Body.Unmarshal(m, b)
}
func (m *Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Body.Marshal(b, m, deterministic)
}
func (m *Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Body.Merge(m, src)
}
func (m *Body) XXX_Size() int {
	return xxx_messageInfo_Body.Size(m)
}
func (m *Body) XXX_DiscardUnknown() {
	xxx_messageInfo_Body.DiscardUnknown(m)
}

var xxx_messageInfo_Body proto.InternalMessageInfo

func (m *Body) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *Body) GetContent() *wrapperspb.BytesValue {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Body) GetContentTypeHint() Body_ContentTypeHint {
	if m != nil {
		return m.ContentTypeHint
	}
	return Body_DEFAULT
}

// Request to preform a comparison on an actual body given the expected one
type CompareContentsRequest struct {
	// Expected body from the Pact interaction
	Expected *Body `protobuf:"bytes,1,opt,name=expected,proto3" json:"expected,omitempty"`
	// Actual received body
	Actual *Body `protobuf:"bytes,2,opt,name=actual,proto3" json:"actual,omitempty"`
	// If unexpected keys or attributes should be allowed. Setting this to false results in additional keys or fields
	// will cause a mismatch
	AllowUnexpectedKeys bool `protobuf:"varint,3,opt,name=allow_unexpected_keys,json=allowUnexpectedKeys,proto3" json:"allow_unexpected_keys,omitempty"`
	// Map of expressions to matching rules. The expressions follow the documented Pact matching rule expressions
	Rules map[string]*MatchingRules `protobuf:"bytes,4,rep,name=rules,proto3" json:"rules,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Additional data added to the Pact/Interaction by the plugin
	PluginConfiguration  *PluginConfiguration `protobuf:"bytes,5,opt,name=pluginConfiguration,proto3" json:"pluginConfiguration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CompareContentsRequest) Reset()         { *m = CompareContentsRequest{} }
func (m *CompareContentsRequest) String() string { return proto.CompactTextString(m) }
func (*CompareContentsRequest) ProtoMessage()    {}
func (*CompareContentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{5}
}

func (m *CompareContentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompareContentsRequest.Unmarshal(m, b)
}
func (m *CompareContentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompareContentsRequest.Marshal(b, m, deterministic)
}
func (m *CompareContentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompareContentsRequest.Merge(m, src)
}
func (m *CompareContentsRequest) XXX_Size() int {
	return xxx_messageInfo_CompareContentsRequest.Size(m)
}
func (m *CompareContentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CompareContentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CompareContentsRequest proto.InternalMessageInfo

func (m *CompareContentsRequest) GetExpected() *Body {
	if m != nil {
		return m.Expected
	}
	return nil
}

func (m *CompareContentsRequest) GetActual() *Body {
	if m != nil {
		return m.Actual
	}
	return nil
}

func (m *CompareContentsRequest) GetAllowUnexpectedKeys() bool {
	if m != nil {
		return m.AllowUnexpectedKeys
	}
	return false
}

func (m *CompareContentsRequest) GetRules() map[string]*MatchingRules {
	if m != nil {
		return m.Rules
	}
	return nil
}

func (m *CompareContentsRequest) GetPluginConfiguration() *PluginConfiguration {
	if m != nil {
		return m.PluginConfiguration
	}
	return nil
}

// Indicates that there was a mismatch with the content type
type ContentTypeMismatch struct {
	// Expected content type (MIME format)
	Expected string `protobuf:"bytes,1,opt,name=expected,proto3" json:"expected,omitempty"`
	// Actual content type received (MIME format)
	Actual               string   `protobuf:"bytes,2,opt,name=actual,proto3" json:"actual,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContentTypeMismatch) Reset()         { *m = ContentTypeMismatch{} }
func (m *ContentTypeMismatch) String() string { return proto.CompactTextString(m) }
func (*ContentTypeMismatch) ProtoMessage()    {}
func (*ContentTypeMismatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{6}
}

func (m *ContentTypeMismatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContentTypeMismatch.Unmarshal(m, b)
}
func (m *ContentTypeMismatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContentTypeMismatch.Marshal(b, m, deterministic)
}
func (m *ContentTypeMismatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContentTypeMismatch.Merge(m, src)
}
func (m *ContentTypeMismatch) XXX_Size() int {
	return xxx_messageInfo_ContentTypeMismatch.Size(m)
}
func (m *ContentTypeMismatch) XXX_DiscardUnknown() {
	xxx_messageInfo_ContentTypeMismatch.DiscardUnknown(m)
}

var xxx_messageInfo_ContentTypeMismatch proto.InternalMessageInfo

func (m *ContentTypeMismatch) GetExpected() string {
	if m != nil {
		return m.Expected
	}
	return ""
}

func (m *ContentTypeMismatch) GetActual() string {
	if m != nil {
		return m.Actual
	}
	return ""
}

// A mismatch for an particular item of content
type ContentMismatch struct {
	// Expected data bytes
	Expected *wrapperspb.BytesValue `protobuf:"bytes,1,opt,name=expected,proto3" json:"expected,omitempty"`
	// Actual data bytes
	Actual *wrapperspb.BytesValue `protobuf:"bytes,2,opt,name=actual,proto3" json:"actual,omitempty"`
	// Description of the mismatch
	Mismatch string `protobuf:"bytes,3,opt,name=mismatch,proto3" json:"mismatch,omitempty"`
	// Path to the item that was matched. This is the value as per the documented Pact matching rule expressions.
	Path string `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	// Optional diff of the contents
	Diff                 string   `protobuf:"bytes,5,opt,name=diff,proto3" json:"diff,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContentMismatch) Reset()         { *m = ContentMismatch{} }
func (m *ContentMismatch) String() string { return proto.CompactTextString(m) }
func (*ContentMismatch) ProtoMessage()    {}
func (*ContentMismatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{7}
}

func (m *ContentMismatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContentMismatch.Unmarshal(m, b)
}
func (m *ContentMismatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContentMismatch.Marshal(b, m, deterministic)
}
func (m *ContentMismatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContentMismatch.Merge(m, src)
}
func (m *ContentMismatch) XXX_Size() int {
	return xxx_messageInfo_ContentMismatch.Size(m)
}
func (m *ContentMismatch) XXX_DiscardUnknown() {
	xxx_messageInfo_ContentMismatch.DiscardUnknown(m)
}

var xxx_messageInfo_ContentMismatch proto.InternalMessageInfo

func (m *ContentMismatch) GetExpected() *wrapperspb.BytesValue {
	if m != nil {
		return m.Expected
	}
	return nil
}

func (m *ContentMismatch) GetActual() *wrapperspb.BytesValue {
	if m != nil {
		return m.Actual
	}
	return nil
}

func (m *ContentMismatch) GetMismatch() string {
	if m != nil {
		return m.Mismatch
	}
	return ""
}

func (m *ContentMismatch) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ContentMismatch) GetDiff() string {
	if m != nil {
		return m.Diff
	}
	return ""
}

// List of content mismatches
type ContentMismatches struct {
	Mismatches           []*ContentMismatch `protobuf:"bytes,1,rep,name=mismatches,proto3" json:"mismatches,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ContentMismatches) Reset()         { *m = ContentMismatches{} }
func (m *ContentMismatches) String() string { return proto.CompactTextString(m) }
func (*ContentMismatches) ProtoMessage()    {}
func (*ContentMismatches) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{8}
}

func (m *ContentMismatches) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContentMismatches.Unmarshal(m, b)
}
func (m *ContentMismatches) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContentMismatches.Marshal(b, m, deterministic)
}
func (m *ContentMismatches) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContentMismatches.Merge(m, src)
}
func (m *ContentMismatches) XXX_Size() int {
	return xxx_messageInfo_ContentMismatches.Size(m)
}
func (m *ContentMismatches) XXX_DiscardUnknown() {
	xxx_messageInfo_ContentMismatches.DiscardUnknown(m)
}

var xxx_messageInfo_ContentMismatches proto.InternalMessageInfo

func (m *ContentMismatches) GetMismatches() []*ContentMismatch {
	if m != nil {
		return m.Mismatches
	}
	return nil
}

// Response to the CompareContentsRequest with the results of the comparison
type CompareContentsResponse struct {
	// Error message if an error occurred. If this field is set, the remaining fields will be ignored and the
	// verification marked as failed
	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// There was a mismatch with the types of content. If this is set, the results may not be set.
	TypeMismatch *ContentTypeMismatch `protobuf:"bytes,2,opt,name=typeMismatch,proto3" json:"typeMismatch,omitempty"`
	// Results of the match, keyed by matching rule expression
	Results              map[string]*ContentMismatches `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *CompareContentsResponse) Reset()         { *m = CompareContentsResponse{} }
func (m *CompareContentsResponse) String() string { return proto.CompactTextString(m) }
func (*CompareContentsResponse) ProtoMessage()    {}
func (*CompareContentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{9}
}

func (m *CompareContentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompareContentsResponse.Unmarshal(m, b)
}
func (m *CompareContentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompareContentsResponse.Marshal(b, m, deterministic)
}
func (m *CompareContentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompareContentsResponse.Merge(m, src)
}
func (m *CompareContentsResponse) XXX_Size() int {
	return xxx_messageInfo_CompareContentsResponse.Size(m)
}
func (m *CompareContentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CompareContentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CompareContentsResponse proto.InternalMessageInfo

func (m *CompareContentsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CompareContentsResponse) GetTypeMismatch() *ContentTypeMismatch {
	if m != nil {
		return m.TypeMismatch
	}
	return nil
}

func (m *CompareContentsResponse) GetResults() map[string]*ContentMismatches {
	if m != nil {
		return m.Results
	}
	return nil
}

// Request to configure/setup an interaction so that it can be verified later
type ConfigureInteractionRequest struct {
	// Content type of the interaction (MIME format)
	ContentType string `protobuf:"bytes,1,opt,name=contentType,proto3" json:"contentType,omitempty"`
	// This is data specified by the user in the consumer test
	ContentsConfig       *structpb.Struct `protobuf:"bytes,2,opt,name=contentsConfig,proto3" json:"contentsConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ConfigureInteractionRequest) Reset()         { *m = ConfigureInteractionRequest{} }
func (m *ConfigureInteractionRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigureInteractionRequest) ProtoMessage()    {}
func (*ConfigureInteractionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{10}
}

func (m *ConfigureInteractionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigureInteractionRequest.Unmarshal(m, b)
}
func (m *ConfigureInteractionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigureInteractionRequest.Marshal(b, m, deterministic)
}
func (m *ConfigureInteractionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigureInteractionRequest.Merge(m, src)
}
func (m *ConfigureInteractionRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigureInteractionRequest.Size(m)
}
func (m *ConfigureInteractionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigureInteractionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigureInteractionRequest proto.InternalMessageInfo

func (m *ConfigureInteractionRequest) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *ConfigureInteractionRequest) GetContentsConfig() *structpb.Struct {
	if m != nil {
		return m.ContentsConfig
	}
	return nil
}

// Represents a matching rule
type MatchingRule struct {
	// Type of the matching rule
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Associated data for the matching rule
	Values               *structpb.Struct `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *MatchingRule) Reset()         { *m = MatchingRule{} }
func (m *MatchingRule) String() string { return proto.CompactTextString(m) }
func (*MatchingRule) ProtoMessage()    {}
func (*MatchingRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{11}
}

func (m *MatchingRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchingRule.Unmarshal(m, b)
}
func (m *MatchingRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchingRule.Marshal(b, m, deterministic)
}
func (m *MatchingRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchingRule.Merge(m, src)
}
func (m *MatchingRule) XXX_Size() int {
	return xxx_messageInfo_MatchingRule.Size(m)
}
func (m *MatchingRule) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchingRule.DiscardUnknown(m)
}

var xxx_messageInfo_MatchingRule proto.InternalMessageInfo

func (m *MatchingRule) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *MatchingRule) GetValues() *structpb.Struct {
	if m != nil {
		return m.Values
	}
	return nil
}

// List of matching rules
type MatchingRules struct {
	Rule                 []*MatchingRule `protobuf:"bytes,1,rep,name=rule,proto3" json:"rule,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MatchingRules) Reset()         { *m = MatchingRules{} }
func (m *MatchingRules) String() string { return proto.CompactTextString(m) }
func (*MatchingRules) ProtoMessage()    {}
func (*MatchingRules) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{12}
}

func (m *MatchingRules) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchingRules.Unmarshal(m, b)
}
func (m *MatchingRules) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchingRules.Marshal(b, m, deterministic)
}
func (m *MatchingRules) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchingRules.Merge(m, src)
}
func (m *MatchingRules) XXX_Size() int {
	return xxx_messageInfo_MatchingRules.Size(m)
}
func (m *MatchingRules) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchingRules.DiscardUnknown(m)
}

var xxx_messageInfo_MatchingRules proto.InternalMessageInfo

func (m *MatchingRules) GetRule() []*MatchingRule {
	if m != nil {
		return m.Rule
	}
	return nil
}

// Example generator
type Generator struct {
	// Type of generator
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Associated data for the generator
	Values               *structpb.Struct `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Generator) Reset()         { *m = Generator{} }
func (m *Generator) String() string { return proto.CompactTextString(m) }
func (*Generator) ProtoMessage()    {}
func (*Generator) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{13}
}

func (m *Generator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Generator.Unmarshal(m, b)
}
func (m *Generator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Generator.Marshal(b, m, deterministic)
}
func (m *Generator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Generator.Merge(m, src)
}
func (m *Generator) XXX_Size() int {
	return xxx_messageInfo_Generator.Size(m)
}
func (m *Generator) XXX_DiscardUnknown() {
	xxx_messageInfo_Generator.DiscardUnknown(m)
}

var xxx_messageInfo_Generator proto.InternalMessageInfo

func (m *Generator) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Generator) GetValues() *structpb.Struct {
	if m != nil {
		return m.Values
	}
	return nil
}

// Plugin configuration added to the pact file by the ConfigureInteraction step
type PluginConfiguration struct {
	// Data to be persisted against the interaction
	InteractionConfiguration *structpb.Struct `protobuf:"bytes,1,opt,name=interactionConfiguration,proto3" json:"interactionConfiguration,omitempty"`
	// Data to be persisted in the Pact file metadata (Global data)
	PactConfiguration    *structpb.Struct `protobuf:"bytes,2,opt,name=pactConfiguration,proto3" json:"pactConfiguration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PluginConfiguration) Reset()         { *m = PluginConfiguration{} }
func (m *PluginConfiguration) String() string { return proto.CompactTextString(m) }
func (*PluginConfiguration) ProtoMessage()    {}
func (*PluginConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{14}
}

func (m *PluginConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginConfiguration.Unmarshal(m, b)
}
func (m *PluginConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginConfiguration.Marshal(b, m, deterministic)
}
func (m *PluginConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginConfiguration.Merge(m, src)
}
func (m *PluginConfiguration) XXX_Size() int {
	return xxx_messageInfo_PluginConfiguration.Size(m)
}
func (m *PluginConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_PluginConfiguration proto.InternalMessageInfo

func (m *PluginConfiguration) GetInteractionConfiguration() *structpb.Struct {
	if m != nil {
		return m.InteractionConfiguration
	}
	return nil
}

func (m *PluginConfiguration) GetPactConfiguration() *structpb.Struct {
	if m != nil {
		return m.PactConfiguration
	}
	return nil
}

// Response to the configure/setup an interaction request
type InteractionResponse struct {
	// Contents for the interaction
	Contents *Body `protobuf:"bytes,1,opt,name=contents,proto3" json:"contents,omitempty"`
	// All matching rules to apply
	Rules map[string]*MatchingRules `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Generators to apply
	Generators map[string]*Generator `protobuf:"bytes,3,rep,name=generators,proto3" json:"generators,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// For message interactions, any metadata to be applied
	MessageMetadata *structpb.Struct `protobuf:"bytes,4,opt,name=messageMetadata,proto3" json:"messageMetadata,omitempty"`
	// Plugin specific data to be persisted in the pact file
	PluginConfiguration *PluginConfiguration `protobuf:"bytes,5,opt,name=pluginConfiguration,proto3" json:"pluginConfiguration,omitempty"`
	// Markdown/HTML formatted text representation of the interaction
	InteractionMarkup     string                         `protobuf:"bytes,6,opt,name=interactionMarkup,proto3" json:"interactionMarkup,omitempty"`
	InteractionMarkupType InteractionResponse_MarkupType `protobuf:"varint,7,opt,name=interactionMarkupType,proto3,enum=io.pact.plugin.InteractionResponse_MarkupType" json:"interactionMarkupType,omitempty"`
	// Description of what part this interaction belongs to (in the case of there being more than one, for instance,
	// request/response messages)
	PartName             string   `protobuf:"bytes,8,opt,name=partName,proto3" json:"partName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InteractionResponse) Reset()         { *m = InteractionResponse{} }
func (m *InteractionResponse) String() string { return proto.CompactTextString(m) }
func (*InteractionResponse) ProtoMessage()    {}
func (*InteractionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{15}
}

func (m *InteractionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InteractionResponse.Unmarshal(m, b)
}
func (m *InteractionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InteractionResponse.Marshal(b, m, deterministic)
}
func (m *InteractionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InteractionResponse.Merge(m, src)
}
func (m *InteractionResponse) XXX_Size() int {
	return xxx_messageInfo_InteractionResponse.Size(m)
}
func (m *InteractionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InteractionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InteractionResponse proto.InternalMessageInfo

func (m *InteractionResponse) GetContents() *Body {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *InteractionResponse) GetRules() map[string]*MatchingRules {
	if m != nil {
		return m.Rules
	}
	return nil
}

func (m *InteractionResponse) GetGenerators() map[string]*Generator {
	if m != nil {
		return m.Generators
	}
	return nil
}

func (m *InteractionResponse) GetMessageMetadata() *structpb.Struct {
	if m != nil {
		return m.MessageMetadata
	}
	return nil
}

func (m *InteractionResponse) GetPluginConfiguration() *PluginConfiguration {
	if m != nil {
		return m.PluginConfiguration
	}
	return nil
}

func (m *InteractionResponse) GetInteractionMarkup() string {
	if m != nil {
		return m.InteractionMarkup
	}
	return ""
}

func (m *InteractionResponse) GetInteractionMarkupType() InteractionResponse_MarkupType {
	if m != nil {
		return m.InteractionMarkupType
	}
	return InteractionResponse_COMMON_MARK
}

func (m *InteractionResponse) GetPartName() string {
	if m != nil {
		return m.PartName
	}
	return ""
}

// Response to the configure/setup an interaction request
type ConfigureInteractionResponse struct {
	// If an error occurred. In this case, the other fields will be ignored/not set
	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// The actual response if no error occurred.
	Interaction []*InteractionResponse `protobuf:"bytes,2,rep,name=interaction,proto3" json:"interaction,omitempty"`
	// Plugin specific data to be persisted in the pact file
	PluginConfiguration  *PluginConfiguration `protobuf:"bytes,3,opt,name=pluginConfiguration,proto3" json:"pluginConfiguration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ConfigureInteractionResponse) Reset()         { *m = ConfigureInteractionResponse{} }
func (m *ConfigureInteractionResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigureInteractionResponse) ProtoMessage()    {}
func (*ConfigureInteractionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{16}
}

func (m *ConfigureInteractionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigureInteractionResponse.Unmarshal(m, b)
}
func (m *ConfigureInteractionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigureInteractionResponse.Marshal(b, m, deterministic)
}
func (m *ConfigureInteractionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigureInteractionResponse.Merge(m, src)
}
func (m *ConfigureInteractionResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigureInteractionResponse.Size(m)
}
func (m *ConfigureInteractionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigureInteractionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigureInteractionResponse proto.InternalMessageInfo

func (m *ConfigureInteractionResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ConfigureInteractionResponse) GetInteraction() []*InteractionResponse {
	if m != nil {
		return m.Interaction
	}
	return nil
}

func (m *ConfigureInteractionResponse) GetPluginConfiguration() *PluginConfiguration {
	if m != nil {
		return m.PluginConfiguration
	}
	return nil
}

// Request to generate the contents using any defined generators
type GenerateContentRequest struct {
	// Original contents
	Contents *Body `protobuf:"bytes,1,opt,name=contents,proto3" json:"contents,omitempty"`
	// Generators to apply
	Generators map[string]*Generator `protobuf:"bytes,2,rep,name=generators,proto3" json:"generators,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Additional data added to the Pact/Interaction by the plugin
	PluginConfiguration  *PluginConfiguration `protobuf:"bytes,3,opt,name=pluginConfiguration,proto3" json:"pluginConfiguration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GenerateContentRequest) Reset()         { *m = GenerateContentRequest{} }
func (m *GenerateContentRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateContentRequest) ProtoMessage()    {}
func (*GenerateContentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{17}
}

func (m *GenerateContentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateContentRequest.Unmarshal(m, b)
}
func (m *GenerateContentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateContentRequest.Marshal(b, m, deterministic)
}
func (m *GenerateContentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateContentRequest.Merge(m, src)
}
func (m *GenerateContentRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateContentRequest.Size(m)
}
func (m *GenerateContentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateContentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateContentRequest proto.InternalMessageInfo

func (m *GenerateContentRequest) GetContents() *Body {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *GenerateContentRequest) GetGenerators() map[string]*Generator {
	if m != nil {
		return m.Generators
	}
	return nil
}

func (m *GenerateContentRequest) GetPluginConfiguration() *PluginConfiguration {
	if m != nil {
		return m.PluginConfiguration
	}
	return nil
}

// Generated body/message response
type GenerateContentResponse struct {
	Contents             *Body    `protobuf:"bytes,1,opt,name=contents,proto3" json:"contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateContentResponse) Reset()         { *m = GenerateContentResponse{} }
func (m *GenerateContentResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateContentResponse) ProtoMessage()    {}
func (*GenerateContentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{18}
}

func (m *GenerateContentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateContentResponse.Unmarshal(m, b)
}
func (m *GenerateContentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateContentResponse.Marshal(b, m, deterministic)
}
func (m *GenerateContentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateContentResponse.Merge(m, src)
}
func (m *GenerateContentResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateContentResponse.Size(m)
}
func (m *GenerateContentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateContentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateContentResponse proto.InternalMessageInfo

func (m *GenerateContentResponse) GetContents() *Body {
	if m != nil {
		return m.Contents
	}
	return nil
}

func init() {
	proto.RegisterEnum("io.pact.plugin.CatalogueEntry_EntryType", CatalogueEntry_EntryType_name, CatalogueEntry_EntryType_value)
	proto.RegisterEnum("io.pact.plugin.Body_ContentTypeHint", Body_ContentTypeHint_name, Body_ContentTypeHint_value)
	proto.RegisterEnum("io.pact.plugin.InteractionResponse_MarkupType", InteractionResponse_MarkupType_name, InteractionResponse_MarkupType_value)
	proto.RegisterType((*InitPluginRequest)(nil), "io.pact.plugin.InitPluginRequest")
	proto.RegisterType((*CatalogueEntry)(nil), "io.pact.plugin.CatalogueEntry")
	proto.RegisterMapType((map[string]string)(nil), "io.pact.plugin.CatalogueEntry.ValuesEntry")
	proto.RegisterType((*InitPluginResponse)(nil), "io.pact.plugin.InitPluginResponse")
	proto.RegisterType((*Catalogue)(nil), "io.pact.plugin.Catalogue")
	proto.RegisterType((*Body)(nil), "io.pact.plugin.Body")
	proto.RegisterType((*CompareContentsRequest)(nil), "io.pact.plugin.CompareContentsRequest")
	proto.RegisterMapType((map[string]*MatchingRules)(nil), "io.pact.plugin.CompareContentsRequest.RulesEntry")
	proto.RegisterType((*ContentTypeMismatch)(nil), "io.pact.plugin.ContentTypeMismatch")
	proto.RegisterType((*ContentMismatch)(nil), "io.pact.plugin.ContentMismatch")
	proto.RegisterType((*ContentMismatches)(nil), "io.pact.plugin.ContentMismatches")
	proto.RegisterType((*CompareContentsResponse)(nil), "io.pact.plugin.CompareContentsResponse")
	proto.RegisterMapType((map[string]*ContentMismatches)(nil), "io.pact.plugin.CompareContentsResponse.ResultsEntry")
	proto.RegisterType((*ConfigureInteractionRequest)(nil), "io.pact.plugin.ConfigureInteractionRequest")
	proto.RegisterType((*MatchingRule)(nil), "io.pact.plugin.MatchingRule")
	proto.RegisterType((*MatchingRules)(nil), "io.pact.plugin.MatchingRules")
	proto.RegisterType((*Generator)(nil), "io.pact.plugin.Generator")
	proto.RegisterType((*PluginConfiguration)(nil), "io.pact.plugin.PluginConfiguration")
	proto.RegisterType((*InteractionResponse)(nil), "io.pact.plugin.InteractionResponse")
	proto.RegisterMapType((map[string]*Generator)(nil), "io.pact.plugin.InteractionResponse.GeneratorsEntry")
	proto.RegisterMapType((map[string]*MatchingRules)(nil), "io.pact.plugin.InteractionResponse.RulesEntry")
	proto.RegisterType((*ConfigureInteractionResponse)(nil), "io.pact.plugin.ConfigureInteractionResponse")
	proto.RegisterType((*GenerateContentRequest)(nil), "io.pact.plugin.GenerateContentRequest")
	proto.RegisterMapType((map[string]*Generator)(nil), "io.pact.plugin.GenerateContentRequest.GeneratorsEntry")
	proto.RegisterType((*GenerateContentResponse)(nil), "io.pact.plugin.GenerateContentResponse")
}

func init() { proto.RegisterFile("plugin.proto", fileDescriptor_22a625af4bc1cc87) }

var fileDescriptor_22a625af4bc1cc87 = []byte{
	// 1303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xcb, 0x6e, 0xdb, 0x46,
	0x17, 0x0e, 0x25, 0x59, 0x96, 0x8e, 0xfc, 0x5b, 0xf2, 0xc8, 0x71, 0x14, 0x26, 0x7f, 0x9a, 0x30,
	0x45, 0x12, 0xb4, 0x01, 0x9d, 0xca, 0x69, 0xd3, 0x16, 0x01, 0x02, 0x59, 0x66, 0x6d, 0xc1, 0x91,
	0x64, 0x8c, 0x69, 0x37, 0x2d, 0x50, 0x18, 0xb4, 0x34, 0x56, 0x04, 0x4b, 0x24, 0x43, 0x0e, 0x93,
	0x6a, 0xd7, 0x65, 0x5f, 0xa4, 0xe8, 0xba, 0xcf, 0xd0, 0x45, 0xf7, 0xed, 0x1b, 0x14, 0xe8, 0x7b,
	0x14, 0x1c, 0x0e, 0x29, 0xde, 0x74, 0x69, 0x53, 0x6f, 0x0c, 0xcd, 0xcc, 0xb9, 0x7f, 0xdf, 0x39,
	0x33, 0x34, 0xac, 0x99, 0x23, 0x67, 0x30, 0xd4, 0x65, 0xd3, 0x32, 0xa8, 0x81, 0xd6, 0x87, 0x86,
	0x6c, 0x6a, 0x3d, 0x2a, 0x7b, 0xbb, 0xe2, 0xed, 0x81, 0x61, 0x0c, 0x46, 0x64, 0x9b, 0x9d, 0x9e,
	0x3b, 0x17, 0xdb, 0x36, 0xb5, 0x1c, 0xf7, 0xd8, 0x5d, 0x8b, 0x77, 0xe2, 0xa7, 0xef, 0x2c, 0xcd,
	0x34, 0x89, 0x65, 0xf3, 0xf3, 0x5b, 0xf1, 0x73, 0x32, 0x36, 0xe9, 0xc4, 0x3b, 0x94, 0x4e, 0x60,
	0xa3, 0xa5, 0x0f, 0xe9, 0x11, 0x73, 0x84, 0xc9, 0x1b, 0x87, 0xd8, 0x14, 0x3d, 0x80, 0xf5, 0xe1,
	0xd8, 0x1c, 0x91, 0x31, 0xd1, 0xa9, 0x46, 0x87, 0x86, 0x5e, 0x13, 0xee, 0x0a, 0x8f, 0x8a, 0x38,
	0xb6, 0x8b, 0x6a, 0xb0, 0xfa, 0x96, 0x58, 0xb6, 0x2b, 0x90, 0x61, 0x02, 0xfe, 0x52, 0xfa, 0x2d,
	0x03, 0xeb, 0x4d, 0x8d, 0x6a, 0x23, 0x63, 0xe0, 0x10, 0x45, 0xa7, 0xd6, 0x04, 0x3d, 0x87, 0x1c,
	0x9d, 0x98, 0x84, 0x99, 0x5a, 0xaf, 0x3f, 0x92, 0xa3, 0x39, 0xca, 0x51, 0x69, 0x99, 0xfd, 0x55,
	0x27, 0x26, 0xc1, 0x4c, 0x0b, 0x55, 0x20, 0x7b, 0x49, 0x26, 0xdc, 0x8d, 0xfb, 0x13, 0xed, 0x42,
	0xfe, 0xad, 0x36, 0x72, 0x88, 0x5d, 0xcb, 0xde, 0xcd, 0x3e, 0x2a, 0xd5, 0x3f, 0x5a, 0x60, 0xf1,
	0x94, 0x09, 0xb3, 0xdf, 0x98, 0x6b, 0x8a, 0x5f, 0x40, 0x29, 0xb4, 0xed, 0x3b, 0x11, 0xa6, 0x4e,
	0x36, 0x61, 0x85, 0x89, 0x72, 0xc7, 0xde, 0xe2, 0xcb, 0xcc, 0xe7, 0x82, 0x74, 0x01, 0xc5, 0x20,
	0x46, 0x54, 0x85, 0x72, 0xb3, 0xdb, 0x51, 0x95, 0x8e, 0x7a, 0xd6, 0x6e, 0xa8, 0xcd, 0x03, 0x05,
	0x57, 0xae, 0xa1, 0xeb, 0xb0, 0xe1, 0x6f, 0xee, 0x2b, 0x1d, 0x05, 0x37, 0xd4, 0x2e, 0xae, 0x08,
	0xa8, 0x0c, 0xa5, 0x76, 0xb7, 0x79, 0x78, 0x76, 0xac, 0xe0, 0x53, 0x05, 0x57, 0x32, 0xa8, 0x04,
	0xab, 0xbe, 0x52, 0xd6, 0x3d, 0x6d, 0x75, 0x54, 0x05, 0x37, 0x9a, 0x6a, 0xab, 0xdb, 0xa9, 0xe4,
	0x24, 0x0c, 0x28, 0x0c, 0x90, 0x6d, 0x1a, 0xba, 0x4d, 0xd0, 0x73, 0x28, 0xf6, 0xfc, 0xf4, 0x6a,
	0x02, 0xcb, 0xff, 0xce, 0xfc, 0xfc, 0xf1, 0x54, 0x41, 0x6a, 0x41, 0x31, 0x38, 0x7c, 0x4f, 0x53,
	0x7f, 0x09, 0x90, 0xdb, 0x35, 0xfa, 0x13, 0x74, 0x17, 0x4a, 0x3d, 0x43, 0xa7, 0x44, 0xa7, 0xaa,
	0x8f, 0x72, 0x11, 0x87, 0xb7, 0xd0, 0xa7, 0xb0, 0xca, 0x97, 0xac, 0x9a, 0xa5, 0xfa, 0x2d, 0xd9,
	0x63, 0xa6, 0xec, 0x33, 0x53, 0xde, 0x9d, 0x50, 0x62, 0x33, 0x44, 0xb0, 0x2f, 0x8b, 0x3a, 0x50,
	0x0e, 0x59, 0x39, 0x18, 0xea, 0xb4, 0x96, 0x65, 0x14, 0xfa, 0x30, 0x1e, 0xa5, 0x1b, 0x87, 0xdc,
	0x8c, 0xca, 0xe2, 0xb8, 0xb2, 0xf4, 0x14, 0xca, 0x31, 0x19, 0x17, 0x81, 0x3d, 0xe5, 0xab, 0xc6,
	0xc9, 0x4b, 0xb5, 0x72, 0x0d, 0x15, 0x20, 0xa7, 0x2a, 0xaf, 0xd4, 0x8a, 0x80, 0x00, 0xf2, 0xbb,
	0xad, 0x4e, 0x03, 0x7f, 0x53, 0xc9, 0x48, 0x3f, 0x65, 0x61, 0xab, 0x69, 0x8c, 0x4d, 0xcd, 0x22,
	0x5c, 0xdb, 0xf6, 0xbb, 0xe5, 0x09, 0x14, 0xc8, 0xf7, 0x26, 0xe9, 0x51, 0xd2, 0x67, 0x69, 0x97,
	0xea, 0x9b, 0x69, 0x91, 0xe1, 0x40, 0x0a, 0x3d, 0x86, 0xbc, 0xd6, 0xa3, 0x8e, 0x36, 0xe2, 0x85,
	0x48, 0x97, 0xe7, 0x32, 0xa8, 0x0e, 0xd7, 0xb5, 0xd1, 0xc8, 0x78, 0x77, 0xe6, 0xe8, 0xbe, 0x85,
	0xb3, 0x4b, 0x32, 0xb1, 0x59, 0x19, 0x0a, 0xb8, 0xca, 0x0e, 0x4f, 0x82, 0xb3, 0x43, 0x32, 0xb1,
	0xd1, 0x3e, 0xac, 0x58, 0xce, 0x88, 0xd8, 0xb5, 0x1c, 0x03, 0xf4, 0x93, 0x04, 0xa0, 0xa9, 0xa9,
	0xc8, 0xd8, 0xd5, 0xf1, 0x30, 0xf6, 0xf4, 0xd1, 0x09, 0x54, 0x3d, 0x95, 0xa6, 0xa1, 0x5f, 0x0c,
	0x07, 0x8e, 0xe5, 0xcd, 0x83, 0x15, 0x16, 0xf7, 0xfd, 0xb8, 0xd9, 0xa3, 0xa4, 0x28, 0x4e, 0xd3,
	0x17, 0xbf, 0x06, 0x98, 0xfa, 0x4a, 0xe9, 0xbb, 0x9d, 0x70, 0xdf, 0x95, 0xea, 0xff, 0x8f, 0x3b,
	0x6a, 0x6b, 0xb4, 0xf7, 0x7a, 0xa8, 0x0f, 0x98, 0x91, 0x70, 0x5b, 0xb6, 0xa0, 0x1a, 0x42, 0xb7,
	0x3d, 0xb4, 0xc7, 0xae, 0x24, 0x12, 0x63, 0x18, 0x15, 0x43, 0x68, 0x6c, 0x45, 0xd0, 0x28, 0xfa,
	0x75, 0x97, 0x7e, 0x15, 0x02, 0xa6, 0x04, 0x76, 0x9e, 0x25, 0xb0, 0x9e, 0x4b, 0xe2, 0xa9, 0x93,
	0x9d, 0x18, 0xe4, 0x73, 0xd5, 0x7c, 0xe4, 0x45, 0x28, 0x8c, 0xb9, 0x67, 0x06, 0x76, 0x11, 0x07,
	0x6b, 0x84, 0x20, 0x67, 0x6a, 0xf4, 0x75, 0x2d, 0xc7, 0xf6, 0xd9, 0x6f, 0x77, 0xaf, 0x3f, 0xbc,
	0xb8, 0x60, 0xe8, 0x14, 0x31, 0xfb, 0x2d, 0xa9, 0xb0, 0x11, 0x4b, 0x82, 0xd8, 0xe8, 0x05, 0xc0,
	0x38, 0x58, 0xf1, 0xa6, 0xff, 0x20, 0xc9, 0x91, 0x88, 0x1a, 0x0e, 0xa9, 0x48, 0x3f, 0x67, 0xe0,
	0x46, 0x82, 0x43, 0x7c, 0x36, 0x6d, 0xc2, 0x0a, 0xb1, 0x2c, 0xc3, 0xe2, 0x85, 0xf6, 0x16, 0x68,
	0x1f, 0xd6, 0x68, 0x08, 0x11, 0x5e, 0x86, 0xfb, 0x33, 0x9c, 0x86, 0xc1, 0xc3, 0x11, 0x45, 0xd4,
	0x81, 0x55, 0x8b, 0xd8, 0xce, 0x88, 0xfa, 0x83, 0xff, 0xe9, 0x42, 0x72, 0x7b, 0x81, 0xc9, 0xd8,
	0x53, 0xf3, 0xf8, 0xed, 0x1b, 0x11, 0xbf, 0x83, 0xb5, 0xf0, 0x41, 0x0a, 0x19, 0x9f, 0x45, 0xc9,
	0x78, 0x6f, 0x41, 0xa1, 0xa2, 0x84, 0xfc, 0x41, 0x80, 0x5b, 0x3e, 0xf7, 0x49, 0x4b, 0xa7, 0xc4,
	0xd2, 0x7a, 0xac, 0x2f, 0xf8, 0xf4, 0x58, 0x3c, 0x37, 0x5f, 0xc0, 0x3a, 0x5f, 0xda, 0x9e, 0x21,
	0x1e, 0xc7, 0x8d, 0x04, 0x85, 0x8e, 0xd9, 0xb3, 0x00, 0xc7, 0xc4, 0xa5, 0x63, 0x58, 0x0b, 0xf7,
	0x8b, 0x4b, 0x13, 0x3a, 0xf5, 0xe5, 0xdd, 0xaf, 0xdb, 0xc1, 0x6d, 0xba, 0xc0, 0x38, 0x17, 0x93,
	0x1a, 0xf0, 0xbf, 0x48, 0x13, 0xa2, 0x27, 0x90, 0x73, 0x47, 0x06, 0x67, 0xd3, 0xed, 0x79, 0x1d,
	0x8b, 0x99, 0xa4, 0x74, 0x04, 0xc5, 0x7d, 0xa2, 0x13, 0x4b, 0xa3, 0x86, 0xf5, 0xdf, 0x04, 0xf5,
	0x8b, 0x00, 0xd5, 0x94, 0x19, 0x84, 0x8e, 0xa1, 0x36, 0x9c, 0x96, 0x3e, 0x3a, 0xca, 0x84, 0xf9,
	0xa6, 0x67, 0x2a, 0x22, 0x05, 0x36, 0xdc, 0x04, 0xa3, 0xd6, 0x16, 0x04, 0x9a, 0xd4, 0x90, 0x7e,
	0xcc, 0x43, 0x35, 0xc2, 0x0b, 0xde, 0x46, 0x4f, 0xa0, 0xe0, 0xe3, 0x38, 0xff, 0x5a, 0xf1, 0xa5,
	0xd0, 0x9e, 0x3f, 0xf4, 0x33, 0x0c, 0x02, 0x39, 0x2e, 0x9e, 0xe2, 0x25, 0x65, 0xe2, 0x1f, 0x03,
	0x0c, 0x7c, 0x54, 0xfc, 0x16, 0xdb, 0x59, 0xc6, 0x54, 0x80, 0x25, 0xb7, 0x17, 0x32, 0x83, 0x1a,
	0x50, 0x1e, 0x13, 0xdb, 0xd6, 0x06, 0xa4, 0x4d, 0xa8, 0xd6, 0xd7, 0xa8, 0xc6, 0x06, 0xd7, 0x9c,
	0x4a, 0xc5, 0xe5, 0xaf, 0xe8, 0x26, 0x42, 0x8f, 0x61, 0x23, 0x84, 0x70, 0x5b, 0xb3, 0x2e, 0x1d,
	0xb3, 0x96, 0x67, 0x24, 0x4c, 0x1e, 0xa0, 0x3e, 0x5c, 0x4f, 0x6c, 0xb2, 0xbe, 0x5d, 0x65, 0x4f,
	0x92, 0xa5, 0x4a, 0x3e, 0xd5, 0xc2, 0xe9, 0xc6, 0xdc, 0xb9, 0x6f, 0x6a, 0x16, 0xed, 0x68, 0x63,
	0x52, 0x2b, 0x78, 0x73, 0xdf, 0x5f, 0x5f, 0xd9, 0xcd, 0x29, 0xbe, 0x82, 0x72, 0x0c, 0xc1, 0x14,
	0xeb, 0xdb, 0x51, 0xeb, 0x37, 0xe3, 0xd6, 0x03, 0x0b, 0xe1, 0x11, 0xf8, 0x10, 0x20, 0x94, 0x5c,
	0x19, 0x4a, 0xcd, 0x6e, 0xbb, 0xdd, 0xed, 0x9c, 0xb5, 0x1b, 0xf8, 0xd0, 0x7b, 0x70, 0x1d, 0xa8,
	0xed, 0x97, 0x15, 0x41, 0xfa, 0x5d, 0x80, 0xdb, 0xe9, 0xb3, 0x72, 0xee, 0xd5, 0xa2, 0x40, 0x29,
	0x54, 0x47, 0xce, 0xfe, 0xfb, 0x4b, 0x40, 0x81, 0xc3, 0x7a, 0xb3, 0x08, 0x96, 0x7d, 0x3f, 0x82,
	0x49, 0x7f, 0x64, 0x60, 0x8b, 0x97, 0xc5, 0xbf, 0x92, 0x42, 0x2f, 0xc7, 0x7f, 0xd8, 0xe2, 0xa7,
	0x91, 0xe6, 0xf4, 0x32, 0xfd, 0x6c, 0x06, 0x08, 0x31, 0x6f, 0x73, 0xfb, 0xf3, 0x6a, 0x72, 0xbf,
	0x42, 0x4e, 0x1d, 0xc2, 0x8d, 0x44, 0x9a, 0xff, 0x76, 0x70, 0xd6, 0xff, 0xcc, 0x02, 0x1c, 0x69,
	0x3d, 0xfe, 0x91, 0xe5, 0x4e, 0xc0, 0xe9, 0x27, 0x17, 0xba, 0x97, 0x24, 0x52, 0xec, 0x7b, 0x59,
	0x94, 0xe6, 0x89, 0xf0, 0xa8, 0xf6, 0xa0, 0x7c, 0x62, 0xf6, 0xdd, 0x70, 0x83, 0x2f, 0xaf, 0x9b,
	0x33, 0x3f, 0xb3, 0xc4, 0xad, 0xc4, 0x58, 0x54, 0xdc, 0x8f, 0x76, 0x74, 0xee, 0x3e, 0x49, 0x23,
	0xaf, 0x1b, 0xf4, 0x60, 0xb9, 0xb7, 0xbd, 0xf8, 0x70, 0xc9, 0x67, 0x12, 0x7a, 0x03, 0x9b, 0x69,
	0x4d, 0x88, 0x3e, 0x4e, 0x79, 0xf7, 0xcc, 0x7a, 0xd6, 0x88, 0x8f, 0x97, 0x13, 0xe6, 0x2e, 0xcf,
	0x03, 0x9e, 0xf8, 0xe1, 0x24, 0xd3, 0x4a, 0x67, 0x75, 0x32, 0xad, 0x19, 0xb4, 0xd8, 0xad, 0x7c,
	0x1b, 0xfb, 0xb7, 0xca, 0x79, 0x9e, 0x15, 0x77, 0xe7, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x55,
	0x0e, 0x03, 0xae, 0x7d, 0x11, 0x00, 0x00,
}
