ARG GO_VERSION=1.27
FROM golang:${GO_VERSION}-alpine

RUN apk add --no-cache curl gcc musl-dev gzip openjdk17-jre bash protoc protobuf-dev file
RUN curl https://mise.run | sh && ln -s /root/.local/bin/mise /usr/local/bin/mise

COPY . /go/src/github.com/pact-foundation/pact-go

WORKDIR /go/src/github.com/pact-foundation/pact-go

CMD ["mise", "run", "test"]
